### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by mgood7123** [jniemann66/ReSampler#6]
how would I compile this for android so I can use this as a library in my application

**Comment by jniemann66** [comment]
Yep sounds good – I’m in !

**Comment by jniemann66** [comment]
Hmm ... that's a good question. 
It's something that has been in the back of mind for a while now, but I haven't got around to trying it.

For a start, the intel SIMD intrinsics in FIRFilter.h will not work on ARM, so they need to be disabled.
However, I as long as __x86_64__ is not defined (which it won't be) I think it will just use the non-SIMD code.
It just means that the FIR filter will be slow since it doesn't have any vectorization (at least until some equivalent ARM code using intrinsics is written)

With regards to the multithreading, I believe the android NDK has basic pthreads support built-in but I'm not sure how it will work.

You also need to think about installing the 3rd party libraries - libsndfile and  fftw64

I think it's probably achievable, but it will be a bit of a rough ride getting there.

Unfortunately, I'm flat-out with other projects at the moment, but when I get some time I might attempt it myself. 

Cheers
Judd

**Comment by mgood7123** [comment]
ok

**Comment by mgood7123** [comment]
[ReSampler.zip](https://github.com/jniemann66/ReSampler/files/3359557/ReSampler.zip)
libfftw3.so
libReSampler.so
( `libsndfile` could not be build as shared due to it requiring `PythonInterp`, and I do not know how to obtain `PythonInterp`
`libsndfile/CMakeLists.txt`
```
if (BUILD_SHARED_LIBS)
	set_package_properties (PythonInterp PROPERTIES
		TYPE REQUIRED
		URL "www.python.org/"
		DESCRIPTION "Python is a widely used high-level programming language."
		PURPOSE "Required to build shared libraries"
		)
endif()
```
`libsndfile/cmake/SndFileChecks.cmake`
```
if (BUILD_SHARED_LIBS)
	find_package (PythonInterp REQUIRED)
endif()
```

first successful build: https://github.com/mgood7123/ReSampler

**Comment by mgood7123** [comment]
test run with 
```
    extern int main(int argc, char * argv[]);
    const char *argv[2];
    argv[0] = "ReSampler";
    argv[1] = "--help";
    main(2, const_cast<char **>(argv));
```
```
V/ReSampler: usage: ReSampler -i <inputfile> [-o <outputfile>] -r <samplerate> [-b <bitformat>] [-n [<normalization factor>]]
    Additional options:
    
    --help
    --version
    --compiler
    --sndfile-version
    --listsubformats <ext>
    --showDitherProfiles
    --gain [<amount>]
    --doubleprecision
    --dither [<amount>] [--autoblank] [--ns [<ID>]] [--flat-tpdf] [--seed [<num>]] [--quantize-bits <number of bits>]
    --noDelayTrim
    --minphase
    --flacCompression <compressionlevel>
    --vorbisQuality <quality>
    --noClippingProtection
    --relaxedLPF
    --steepLPF
    --lpf-cutoff <percentage> [--lpf-transition <percentage>]
    --mt
    --rf64
    --noPeakChunk
    --noMetadata
    --singleStage
    --multiStage
    --maxStages
    --showStages
    --showTempFile
    --noTempFile
Application terminated.
```

**Comment by jniemann66** [comment]
Looks like you made a lot of progress - well done !
with the assertAlignment() - its just trying to confirm that there is 32-byte alignment for the benefit of potential AVX instructions. Since in Android, we won't need the 32-bit alignment. You could comment the alignment stuff out for android-only. (at least until we start using future neon instructions in lieu of SSE / AVX).

In regards to the raw input, that definitely won't work until I add some code to do it (on any platform). I haven't really needed it until now, but will add it. (It's not libsndfiles' fault, it's something that ReSampler needs to have added)

I will probably get to have a look at that on the weekend

**Comment by mgood7123** [comment]
ok, ill try that

**Comment by mgood7123** [comment]
also NOTE that this is considered a temporary fix, as I have has builds like this that randomly fail after a while and appear to be related to old cmake files in particular not fully cleaning the project before building it, I have yet to confirm that this is actually what is causes it to fail sometimes

**Comment by mgood7123** [comment]
made `main` reentraint,
made android output natual (no longer relies on ANDROID_OUT and ANDROID_ERR for outputting)
srconvert appears to hang between stage 1 and stage 2 in android, cause is unknown

**Comment by jniemann66** [comment]
I suspect the crashing is related to the aligned malloc not working properly on android for some reason.
The alignment assertions we were getting before were probably telling us something.
 I'm checking it out now ...

**Comment by mgood7123** [comment]
ok, also what is the CORRECT indentation for ReSampler.cpp?

**Comment by jniemann66** [comment]
Crashing on deallocating FIR kernel buffers when in scalar mode should be fixed now,
Given that you've got it to at least compile on Android now, I'm going to close this.
Good Work !

**Comment by mgood7123** [comment]
ok

**Comment by jniemann66** [comment]
Yeah, sorry about that – In this particular case, I think this was a result of using Visual Studio and hitting the ‘format selection’ function. That must have done something with the whitespace.

 

The thing is, I use a lot of different editors/IDEs – depending on what the OS and machine I’m using is (and I have Linux / Mac/ Windows noxes), the editor could be Windows + Visual studio, VSCode, QtCreator, CLion, or just plain old VIM etc – and they might not be set up consistently !

 

I guess it should be 4 spaces. I’ll see if I can clean it up

**Comment by jniemann66** [comment]
Actually, I think I’d like to use tabs, Most of the existing files have tabs, but I see a few spaces have crept in !

I’ll clean it all up … maybe not tonight, though …

 

 

From: Judd Niemann [mailto:jniemann666@bigpond.com] 
Sent: Sunday, July 7, 2019 11:00 PM
To: 'jniemann66/ReSampler'
Subject: RE: [jniemann66/ReSampler] Android (#6)

 

Yeah, sorry about that – In this particular case, I think this was a result of using Visual Studio and hitting the ‘format selection’ function. That must have done something with the whitespace.

 

The thing is, I use a lot of different editors/IDEs – depending on what the OS and machine I’m using is (and I have Linux / Mac/ Windows noxes), the editor could be Windows + Visual studio, VSCode, QtCreator, CLion, or just plain old VIM etc – and they might not be set up consistently !

 

I guess it should be 4 spaces. I’ll see if I can clean it up

**Comment by mgood7123** [comment]
ok
